alter table SYS_SCHEDULED_TASK add constraint FK_SYS_SCHEDULED_TASK_ON_DB_SCRIPT foreign key (DB_SCRIPT_ID) references DDCSD_SCRIPT(ID);
create index IDX_SYS_SCHEDULED_TASK_ON_DB_SCRIPT on SYS_SCHEDULED_TASK (DB_SCRIPT_ID);
