alter table DDCSD_SCRIPT add constraint FK_DDCSD_SCRIPT_ON_CATEGORY foreign key (CATEGORY_ID) references DDCSD_SCRIPT_CATEGORY(ID);
create index IDX_DDCSD_SCRIPT_ON_CATEGORY on DDCSD_SCRIPT (CATEGORY_ID);
